---
# defaults file for roles/cont_mariadb

LISTEN_PORT: 3306
container_name: mariadb
systemd_TimeoutStartSec: 15
container_run_as_user: root
container_run_args:   -p {{LISTEN_PORT}}:3306  -v /srv/mariadb2:/config -e PUID=1000 -e PGUID=1000 -e MYSQL_ROOT_PASSWORD={{MYSQL_ROOT_PASSWORD}} -e MYSQL_DATABASE=nextcloud -e MYSQL_USER=nextcloud -e MYSQL_PASSWORD={{MYSQL_PASSWORD}} -e TZ=Europe/Berlin
container_image: linuxserver/mariadb
container_cmd_args:
container_stop_timeout: 15
container_restart: on-failure
systemd_RestartSec: 30