#- name: "setzen der notwendigen variablen"
 # vars:
    #LISTEN_PORT: 8085
    #container_name: signal-cli-rest-api
    #systemd_TimeoutStartSec: 15
    #container_run_as_user: root
    #container_run_args:  -p {{LISTEN_PORT}}:8080 -v /srv/signal-cli-rest-api/:/home/.local/share/signal-cli
    #container_image: nextcloud
    #container_cmd_args:
    #container_stop_timeout: 15
    #container_restart: on-failure
    #systemd_RestartSec: 30

- name: "pull das nextcloud image"
  podman_image:
    name: '{{container_image}}'

- name: "Create  the nextcloud volume directory"
  file:
    path: /srv/nextcloud/config
    state: directory
    mode: '0755'
- name: "Create  the nextcloud volume directory"
  file:
    path: /srv/nextcloud/apps
    state: directory
    mode: '0755'
- name: "Create  the nextcloud volume directory"
  file:
    path: /srv/nextcloud/data
    state: directory
    mode: '0755'

- name: "create systemd service file for container: {{ container_name }}"
  template:
    src: systemd-service-single.j2
    dest: "/etc/systemd/system/{{container_name}}.service"
    owner: root
    group: root
    mode: 0644
    force: yes
  notify: reload systemctl
- name: "start {{ container_name }} service"
  systemd:
    name: "{{container_name}}"
    daemon_reload: true
    state: restarted
    enabled: yes