- name: get service facts
  service_facts:

- name: "stop {{ container_name }} service"
  systemd:
    name: "{{container_name}}"
    state: stopped
    enabled: yes
  when: ansible_facts.services["{{ container_name }}.service"] is defined

- name: "pull das nextcloud image"
  podman_image:
    name: '{{container_image}}'

- name: "Create  the nextcloud config directory"
  file:
    path: /srv/nextcloud2/config
    state: directory
    mode: '0755'
    
- name: "Create  the nextcloud data directory"
  file:
    path: /srv/nextcloud2/data
    state: directory
    mode: '0755'

- name: "create systemd service file for container: {{ container_name }}"
  template:
    src: systemd-service-single.j2
    dest: "/etc/systemd/system/{{container_name}}.service"
    owner: root
    group: root
    mode: 0644
    force: yes
  notify: reload systemctl

- name: "start {{ container_name }} service"
  systemd:
    name: "{{container_name}}"
    daemon_reload: true
    state: restarted
    enabled: yes

- name: "set nextcloud ip to variable nextcloud_ip"
  shell: "podman inspect --format '{''{ .NetworkSettings.IPAddress }''}' nextcloud"
  register: nextcloud_ip