---
# defaults file for roles/install_nextcloud

LISTEN_PORT: 8080
container_name: nextcloud
systemd_TimeoutStartSec: 15
container_run_as_user: root
container_run_args:   -p {{LISTEN_PORT}}:443 -v /srv/nextcloud2/config:/config -v /srv/nextcloud2/data:/data -e PUID=1000 -e PGID=1000 -e TZ=Europe/Berlin 
container_image: linuxserver/nextcloud
container_cmd_args:
container_stop_timeout: 15
container_restart: on-failure
systemd_RestartSec: 30