---
# defaults file for roles/install_nextcloud

LISTEN_PORT: 8080
container_name: nextcloud
systemd_TimeoutStartSec: 15
container_run_as_user: root
container_run_args:  --pod nextcloud -p {{LISTEN_PORT}}:80 -v /srv/nextcloud/apps:/var/www/html/apps -v /srv/nextcloud/config:/var/www/html/config -v /srv/nextcloud/data:/var/www/html/data -e VIRTUAL_HOST=files.bolay.org -e VIRTUAL_PORT=80 
container_image: nextcloud
container_cmd_args:
container_stop_timeout: 15
container_restart: on-failure
systemd_RestartSec: 30